In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset
df = pd.read_csv("/content/creditcard.csv")
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [3]:
df.shape

(140703, 31)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140703 entries, 0 to 140702
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    140703 non-null  int64
 1   V1      140703 non-null  float64
 2   V2      140703 non-null  float64
 3   V3      140703 non-null  float64
 4   V4      140703 non-null  float64
 5   V5      140702 non-null  float64
 6   V6      140702 non-null  float64
 7   V7      140702 non-null  float64
 8   V8      140702 non-null  float64
 9   V9      140702 non-null  float64
 10  V10     140702 non-null  float64
 11  V11     140702 non-null  float64
 12  V12     140702 non-null  float64
 13  V13     140702 non-null  float64
 14  V14     140702 non-null  float64
 15  V15     140702 non-null  float64
 16  V16     140702 non-null  float64
 17  V17     140702 non-null  float64
 18  V18     140702 non-null  float64
 19  V19     140702 non-null  float64
 20  V20     140702 non-null  float64
 21  V21     140702 non-null  float64
 22  V22     140702 non-null  float64
 23  V23     140702 non-null  float64
 24  V24     140702 non-null  float64
 25  V25     140702 non-null  float64
 26  V26     140702 non-null  float64
 27  V27     140702 non-null  float64
 28  V28     140702 non-null  float64
 29  Amount  140702 non-null  float64
 30  Class   140702 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 33.3 MB

In [8]:
# number of missing values
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        1
V6        1
V7        1
V8        1
V9        1
V10       1
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
df = df.dropna()

In [10]:
df.shape

(140702, 31)

In [12]:
# distribution of legit & fraudulent transactions
df['Class'].value_counts()

Class
0.0    140438
1.0       264
Name: count, dtype: int64

There is some imbalance in the data.

There are a lot more legit than fraudulent transactions and if the model is trained with this data, it wont be able to fully recognize the fraudulent ones.

0 --> Legit Transaction

1 --> Fraudulent Transaction

In [18]:
# separating the data for analysis

legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [19]:
print(legit.shape)
print(fraud.shape)

(140438, 31)
(264, 31)

In [15]:
legit.Amount.describe()

count    140438.000000
mean         91.068217
std         247.065709
min           0.000000
25%           6.000000
50%          23.900000
75%          80.760000
max       19656.530000
Name: Amount, dtype: float64

In [16]:
fraud.Amount.describe()

count     264.000000
mean      115.387008
std       245.189867
min         0.000000
25%         1.000000
50%         9.560000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [17]:
# compare the values of both transactions

df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,52034.876842,-0.239504,0.011245,0.687392,0.131415,-0.275448,0.082153,-0.106135,0.062394,-0.088075,...,0.042180,-0.041927,-0.118336,-0.033151,0.012195,0.130022,0.023506,-0.000321,0.002165,91.068217
1.0,42420.212121,-5.610819,3.946507,-7.143814,4.512206,-3.977333,-1.480669,-5.936405,1.508791,-2.604923,...,0.239899,1.256981,-0.311690,-0.116543,-0.107463,0.197988,0.056528,0.489643,0.081783,115.387008

Dealing with the Unbalanced Data

Under-Sampling: Build a sample dataset containing similar distribution of legit transaction, and fraudulent transaction

Number of Fraudulent Tansactions --> 264

In [20]:
legit_sample = legit.sample(n=264)

Concatenating two DataFrames

In [21]:
new_df = pd.concat([legit_sample, fraud], axis = 0)

In [22]:
new_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
138977,82947,-1.661095,0.936779,1.115652,-1.376219,-0.596237,-0.571034,-0.070109,0.768926,0.230429,...,-0.040070,-0.155854,0.014463,0.204025,-0.422403,0.736014,0.371144,0.198988,20.67,0.0
131243,79533,1.238521,0.233107,0.642831,0.701037,-0.674317,-1.189856,0.041155,-0.204001,0.082337,...,-0.240958,-0.716025,0.182325,0.695596,0.160797,0.075730,-0.031050,0.021349,0.99,0.0
72977,54930,1.276269,-1.712864,1.458407,-0.873921,-2.228470,0.745280,-1.920578,0.469954,-0.542397,...,-0.374652,-0.330497,0.098749,0.203019,0.190897,-0.209512,0.099944,0.018465,32.00,0.0
75918,56308,1.168745,0.232425,0.329970,0.870799,0.032201,0.087998,-0.071363,0.113349,-0.198216,...,0.004972,0.044857,-0.045722,-0.330194,0.485913,-0.405849,0.035129,0.008910,5.00,0.0
104190,68952,1.117068,-0.098310,1.332002,1.338130,-1.103185,-0.092575,-0.751531,0.275856,0.642229,...,0.170975,0.578040,-0.056054,0.515574,0.405678,-0.267391,0.056629,0.024159,1.00,0.0

In [23]:
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
125342,77627,-7.139060,2.773082,-6.757845,4.446456,-5.464428,-1.713401,-6.485365,3.409395,-3.053493,...,1.303250,-0.016118,-0.876670,0.382230,-1.054624,-0.614606,-0.766848,0.409424,106.90,1.0
128479,78725,-4.312479,1.886476,-2.338634,-0.475243,-1.185444,-2.112079,-2.122793,0.272565,0.290273,...,0.550541,-0.067870,-1.114692,0.269069,-0.020572,-0.963489,-0.918888,0.001454,60.00,1.0
131272,79540,-0.114361,1.036129,1.984405,3.128243,-0.740344,1.548619,-1.701284,-2.203842,-1.242265,...,-1.032935,1.196428,-0.112857,0.254719,0.696668,0.482370,0.129969,0.223924,0.20,1.0
135718,81372,-0.885254,1.790649,-0.945149,3.853433,-1.543510,0.188582,-2.988383,1.344059,-2.294535,...,0.746160,0.550802,-0.034882,-0.567608,-0.528318,0.258782,0.506893,0.176736,7.57,1.0
137705,82289,-1.464897,1.975528,-1.077145,2.819191,0.069850,-0.789044,-1.196101,0.673654,-1.363724,...,0.174099,-0.272505,-0.031549,-0.406166,0.157769,-0.104393,0.073796,-0.041570,1.00,1.0

In [24]:
new_df['Class'].value_counts()

Class
0.0    264
1.0    264
Name: count, dtype: int64

In [25]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,53173.715909,-0.177387,0.046781,0.564367,0.222390,-0.234991,0.207841,-0.045450,0.102574,-0.061105,...,0.097953,-0.066404,-0.151943,0.026423,-0.043415,0.187745,-0.034990,0.007547,0.006915,97.217841
1.0,42420.212121,-5.610819,3.946507,-7.143814,4.512206,-3.977333,-1.480669,-5.936405,1.508791,-2.604923,...,0.239899,1.256981,-0.311690,-0.116543,-0.107463,0.197988,0.056528,0.489643,0.081783,115.387008

Splitting the data into Features and Targets

In [31]:
X = new_df.iloc[:, :-1]
Y = new_df.iloc[:, -1]
print(Y)
#print(X.shape)

138977    0.0
131243    0.0
72977     0.0
75918     0.0
104190    0.0
         ...
125342    1.0
128479    1.0
131272    1.0
135718    1.0
137705    1.0
Name: Class, Length: 528, dtype: float64

Split data inot training and test data

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [34]:
X_train.shape

(422, 30)

Model Training

Logistic Regression

In [35]:
model = LogisticRegression()

In [36]:
#training the logistic regression model with training data
model.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

In [37]:
# accuracy on training data
X_train_pred = model.predict(X_train)

training_data_accuracy = accuracy_score(X_train_pred, Y_train)

print(f"Accuracy on training data {training_data_accuracy}")

Accuracy on training data 0.9502369668246445

In [38]:
# accuracy on test data
X_test_pred = model.predict(X_test)

test_data_accuracy = accuracy_score(X_test_pred, Y_test)

print(f"Accuracy on test data {test_data_accuracy}")

Accuracy on test data 0.9716981132075472

Building the Predictive System

In [41]:
input_data = (0,-1.3598071336738,-0.0727811733098497,2.53634673796914,1.37815522427443,-0.338320769942518,0.462387777762292,0.239598554061257,0.0986979012610507,0.363786969611213,0.0907941719789316,-0.551599533260813,-0.617800855762348,-0.991389847235408,-0.311169353699879,1.46817697209427,-0.470400525259478,0.207971241929242,0.0257905801985591,0.403992960255733,0.251412098239705,-0.018306777944153,0.277837575558899,-0.110473910188767,0.0669280749146731,0.128539358273528,-0.189114843888824,0.133558376740387,-0.0210530534538215,149.62)

# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array since we are predicting for one data point
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if prediction[0] == 0:
  print("The transaction is legit")
else:
  print("The transaction is fradulent")

[1.]
The transaction is fradulent

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(